### ISSUE TITLE
大神，最近公司有K先功能参考了你带代码，发现一个bug我不知道怎么解决，急需帮助

### ISSUE THREAD

**Issue by ganjmeng** [volcs/StockChart#1]
大神，最近公司有K先功能参考了你带代码，发现一个bug我不知道怎么解决，急需帮助，K线日线，周线，月线图放大没问题，但是缩小的时候K线每次都会跳到最左边那个，不知道怎么解决，求助！！

**Comment by czing8** [comment]
最新的代码修改这个bug了

**Comment by ganjmeng** [comment]
多谢大神
